version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dupword
    - durationcheck
    # Probably better to enable this, but too many existing errors.
    # - err113
    - errchkjson
    - errname
    - exhaustive
    # Probably better to enable this, but too many existing errors.
    # - exhaustruct
    - exptostd
    - fatcontext
    - gocheckcompilerdirectives
    - gochecksumtype
    - gocritic
    - godot
    - goprintffuncname
    - gosec
    - iface
    - importas
    - intrange
    - makezero
    - mirror
    - misspell
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - reassign
    - recvcheck
    # Probably better to enable this, but too many existing errors.
    # - revive
    - testifylint
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
